version: '3.4'

services:
  in.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "60050:80"
  out.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "60051:80"
networks:
  default:
    external:
      name: nat